# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/yjay.kim/git/cgreclaim

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/yjay.kim/git/cgreclaim

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/yjay.kim/git/cgreclaim/CMakeFiles /home/yjay.kim/git/cgreclaim//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/yjay.kim/git/cgreclaim/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named cgreclaim

# Build rule for target.
cgreclaim: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 cgreclaim
.PHONY : cgreclaim

# fast build rule for target.
cgreclaim/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cgreclaim.dir/build.make CMakeFiles/cgreclaim.dir/build
.PHONY : cgreclaim/fast

#=============================================================================
# Target rules for targets named test_cgreclaim

# Build rule for target.
test_cgreclaim: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_cgreclaim
.PHONY : test_cgreclaim

# fast build rule for target.
test_cgreclaim/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_cgreclaim.dir/build.make CMakeFiles/test_cgreclaim.dir/build
.PHONY : test_cgreclaim/fast

cgr_log.o: cgr_log.c.o
.PHONY : cgr_log.o

# target to build an object file
cgr_log.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cgreclaim.dir/build.make CMakeFiles/cgreclaim.dir/cgr_log.c.o
.PHONY : cgr_log.c.o

cgr_log.i: cgr_log.c.i
.PHONY : cgr_log.i

# target to preprocess a source file
cgr_log.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cgreclaim.dir/build.make CMakeFiles/cgreclaim.dir/cgr_log.c.i
.PHONY : cgr_log.c.i

cgr_log.s: cgr_log.c.s
.PHONY : cgr_log.s

# target to generate assembly for a file
cgr_log.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cgreclaim.dir/build.make CMakeFiles/cgreclaim.dir/cgr_log.c.s
.PHONY : cgr_log.c.s

cgreclaim.o: cgreclaim.c.o
.PHONY : cgreclaim.o

# target to build an object file
cgreclaim.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cgreclaim.dir/build.make CMakeFiles/cgreclaim.dir/cgreclaim.c.o
.PHONY : cgreclaim.c.o

cgreclaim.i: cgreclaim.c.i
.PHONY : cgreclaim.i

# target to preprocess a source file
cgreclaim.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cgreclaim.dir/build.make CMakeFiles/cgreclaim.dir/cgreclaim.c.i
.PHONY : cgreclaim.c.i

cgreclaim.s: cgreclaim.c.s
.PHONY : cgreclaim.s

# target to generate assembly for a file
cgreclaim.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cgreclaim.dir/build.make CMakeFiles/cgreclaim.dir/cgreclaim.c.s
.PHONY : cgreclaim.c.s

cgroup.o: cgroup.c.o
.PHONY : cgroup.o

# target to build an object file
cgroup.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cgreclaim.dir/build.make CMakeFiles/cgreclaim.dir/cgroup.c.o
.PHONY : cgroup.c.o

cgroup.i: cgroup.c.i
.PHONY : cgroup.i

# target to preprocess a source file
cgroup.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cgreclaim.dir/build.make CMakeFiles/cgreclaim.dir/cgroup.c.i
.PHONY : cgroup.c.i

cgroup.s: cgroup.c.s
.PHONY : cgroup.s

# target to generate assembly for a file
cgroup.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cgreclaim.dir/build.make CMakeFiles/cgreclaim.dir/cgroup.c.s
.PHONY : cgroup.c.s

monitor.o: monitor.c.o
.PHONY : monitor.o

# target to build an object file
monitor.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cgreclaim.dir/build.make CMakeFiles/cgreclaim.dir/monitor.c.o
.PHONY : monitor.c.o

monitor.i: monitor.c.i
.PHONY : monitor.i

# target to preprocess a source file
monitor.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cgreclaim.dir/build.make CMakeFiles/cgreclaim.dir/monitor.c.i
.PHONY : monitor.c.i

monitor.s: monitor.c.s
.PHONY : monitor.s

# target to generate assembly for a file
monitor.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cgreclaim.dir/build.make CMakeFiles/cgreclaim.dir/monitor.c.s
.PHONY : monitor.c.s

test.o: test.c.o
.PHONY : test.o

# target to build an object file
test.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_cgreclaim.dir/build.make CMakeFiles/test_cgreclaim.dir/test.c.o
.PHONY : test.c.o

test.i: test.c.i
.PHONY : test.i

# target to preprocess a source file
test.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_cgreclaim.dir/build.make CMakeFiles/test_cgreclaim.dir/test.c.i
.PHONY : test.c.i

test.s: test.c.s
.PHONY : test.s

# target to generate assembly for a file
test.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_cgreclaim.dir/build.make CMakeFiles/test_cgreclaim.dir/test.c.s
.PHONY : test.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... cgreclaim"
	@echo "... test_cgreclaim"
	@echo "... cgr_log.o"
	@echo "... cgr_log.i"
	@echo "... cgr_log.s"
	@echo "... cgreclaim.o"
	@echo "... cgreclaim.i"
	@echo "... cgreclaim.s"
	@echo "... cgroup.o"
	@echo "... cgroup.i"
	@echo "... cgroup.s"
	@echo "... monitor.o"
	@echo "... monitor.i"
	@echo "... monitor.s"
	@echo "... test.o"
	@echo "... test.i"
	@echo "... test.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

